import { Footer } from '@/Components/Footer'
import './globals.css'
import { Inter } from 'next/font/google'
import Layout from '@/Components/Layout/Layout'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div className=' bg-[#1F2025] '>
        <body className={inter.className}>
          <Layout>
            {children}
          </Layout>
        </body>
      </div>
    </html>
  )
}
